### ISSUE TITLE
sample data for mongo startup

### ISSUE THREAD

**Issue by jakegk22** [imaolo/yaat#1]
could you add some of the sample data for the eth_tickers, so I can verify my enviroment?
I got no clue where I put my tickers.json lol

thx bby

**Comment by imaolo** [comment]
yeah ill push a script to grab the data from the google drive and put it in the right place.

**Comment by imaolo** [comment]
it can unzip and import into mongodb

**Comment by imaolo** [comment]
ill push eth_tickers.json in the meantime, its not big

**Comment by imaolo** [comment]
eth_tickers.json is 50MB too large for gh, hang tight for data.py

**Comment by imaolo** [comment]
see data.py
